# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\nbase.proto\"*\n\x0b_64ByteList\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c._64ByteItem\"7\n\x0b_64ByteItem\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x1c\n\tdata_type\x18\x02 \x01(\x0e\x32\t.DataType\"*\n\x0b_32ByteList\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c._32ByteItem\"7\n\x0b_32ByteItem\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1c\n\tdata_type\x18\x02 \x01(\x0e\x32\t.DataType\"Z\n\r_BaseListInfo\x12\x0b\n\x03ids\x18\x01 \x03(\x04\x12\x0b\n\x03gid\x18\x02 \x01(\x04\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12\x11\n\tcover_url\x18\x05 \x01(\t*\x86\x01\n\x08\x44\x61taType\x12\x13\n\x0f\x44\x41TA_TYPE_NOVEL\x10\x00\x12\x13\n\x0f\x44\x41TA_TYPE_COMIC\x10\x01\x12\x13\n\x0f\x44\x41TA_TYPE_VIDEO\x10\x02\x12\x13\n\x0f\x44\x41TA_TYPE_GROUP\x10\x03\x12\x13\n\x0f\x44\x41TA_TYPE_EBOOK\x10\x04\x12\x11\n\rDATA_TYPE_ALL\x10\n'
)

_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_NOVEL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_COMIC', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_VIDEO', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_GROUP', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_EBOOK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_TYPE_ALL', index=5, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=309,
  serialized_end=443,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
DATA_TYPE_NOVEL = 0
DATA_TYPE_COMIC = 1
DATA_TYPE_VIDEO = 2
DATA_TYPE_GROUP = 3
DATA_TYPE_EBOOK = 4
DATA_TYPE_ALL = 10



__64BYTELIST = _descriptor.Descriptor(
  name='_64ByteList',
  full_name='_64ByteList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='_64ByteList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=56,
)


__64BYTEITEM = _descriptor.Descriptor(
  name='_64ByteItem',
  full_name='_64ByteItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='_64ByteItem.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='_64ByteItem.data_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=113,
)


__32BYTELIST = _descriptor.Descriptor(
  name='_32ByteList',
  full_name='_32ByteList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='_32ByteList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=157,
)


__32BYTEITEM = _descriptor.Descriptor(
  name='_32ByteItem',
  full_name='_32ByteItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='_32ByteItem.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='_32ByteItem.data_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=214,
)


__BASELISTINFO = _descriptor.Descriptor(
  name='_BaseListInfo',
  full_name='_BaseListInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='_BaseListInfo.ids', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gid', full_name='_BaseListInfo.gid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='_BaseListInfo.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='_BaseListInfo.author', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cover_url', full_name='_BaseListInfo.cover_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=306,
)

__64BYTELIST.fields_by_name['items'].message_type = __64BYTEITEM
__64BYTEITEM.fields_by_name['data_type'].enum_type = _DATATYPE
__32BYTELIST.fields_by_name['items'].message_type = __32BYTEITEM
__32BYTEITEM.fields_by_name['data_type'].enum_type = _DATATYPE
DESCRIPTOR.message_types_by_name['_64ByteList'] = __64BYTELIST
DESCRIPTOR.message_types_by_name['_64ByteItem'] = __64BYTEITEM
DESCRIPTOR.message_types_by_name['_32ByteList'] = __32BYTELIST
DESCRIPTOR.message_types_by_name['_32ByteItem'] = __32BYTEITEM
DESCRIPTOR.message_types_by_name['_BaseListInfo'] = __BASELISTINFO
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_64ByteList = _reflection.GeneratedProtocolMessageType('_64ByteList', (_message.Message,), {
  'DESCRIPTOR' : __64BYTELIST,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:_64ByteList)
  })
_sym_db.RegisterMessage(_64ByteList)

_64ByteItem = _reflection.GeneratedProtocolMessageType('_64ByteItem', (_message.Message,), {
  'DESCRIPTOR' : __64BYTEITEM,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:_64ByteItem)
  })
_sym_db.RegisterMessage(_64ByteItem)

_32ByteList = _reflection.GeneratedProtocolMessageType('_32ByteList', (_message.Message,), {
  'DESCRIPTOR' : __32BYTELIST,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:_32ByteList)
  })
_sym_db.RegisterMessage(_32ByteList)

_32ByteItem = _reflection.GeneratedProtocolMessageType('_32ByteItem', (_message.Message,), {
  'DESCRIPTOR' : __32BYTEITEM,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:_32ByteItem)
  })
_sym_db.RegisterMessage(_32ByteItem)

_BaseListInfo = _reflection.GeneratedProtocolMessageType('_BaseListInfo', (_message.Message,), {
  'DESCRIPTOR' : __BASELISTINFO,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:_BaseListInfo)
  })
_sym_db.RegisterMessage(_BaseListInfo)


# @@protoc_insertion_point(module_scope)
