# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: disk_file_system.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='disk_file_system.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16\x64isk_file_system.proto\"p\n\x0fRealTimeRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12 \n\x0bsource_type\x18\x03 \x01(\x0e\x32\x0b.dataSource\x12\x1f\n\x07operate\x18\x04 \x01(\x0e\x32\x0e.RealTimeRecOp\"M\n\x10RealTimeResponse\x12\x19\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0b.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\"9\n\ttest_data\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06str_id\x18\x02 \x01(\t\x12\x10\n\x08str_data\x18\x03 \x01(\t\")\n\tbase_info\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\x05\"V\n\x04user\x12\x19\n\x05test1\x18\x01 \x03(\x0b\x32\n.test_data\x12\x18\n\x04\x62\x61se\x18\x02 \x01(\x0b\x32\n.base_info\x12\x19\n\x05test2\x18\x03 \x03(\x0b\x32\n.test_data*y\n\nStatusCode\x12\x15\n\x11StatusCodeSuccess\x10\x00\x12\x1c\n\x18StatusCodeInvalidRequest\x10\x01\x12\x18\n\x14StatusCodeBshelfFail\x10\x02\x12\x1c\n\x18StatusCodeBshelfRedisErr\x10\x03*\xd9\x01\n\ndataSource\x12\x11\n\rUnknownSource\x10\x00\x12\x14\n\x10XST_UserBehavior\x10\x0c\x12\x13\n\x0fXST_UserProfile\x10\r\x12\x0e\n\nXST_Recall\x10\x0e\x12\x14\n\x10HHM_UserBehavior\x10\x0f\x12\x13\n\x0fHHM_UserProfile\x10\x10\x12\x0e\n\nHHM_Recall\x10\x11\x12\x17\n\x13\x41\x62road_UserBehavior\x10\x13\x12\x16\n\x12\x41\x62road_UserProfile\x10\x14\x12\x11\n\rAbroad_Recall\x10\x15*V\n\rRealTimeRecOp\x12\x15\n\x11RealTimeRecUnkonw\x10\x00\x12\x16\n\x12RealTimeRecGetData\x10\x01\x12\x16\n\x12RealTimeRecSetData\x10\x02\x62\x06proto3'
)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='StatusCodeSuccess', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StatusCodeInvalidRequest', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StatusCodeBshelfFail', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='StatusCodeBshelfRedisErr', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=409,
  serialized_end=530,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
_DATASOURCE = _descriptor.EnumDescriptor(
  name='dataSource',
  full_name='dataSource',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnknownSource', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XST_UserBehavior', index=1, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XST_UserProfile', index=2, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XST_Recall', index=3, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HHM_UserBehavior', index=4, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HHM_UserProfile', index=5, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HHM_Recall', index=6, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Abroad_UserBehavior', index=7, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Abroad_UserProfile', index=8, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Abroad_Recall', index=9, number=21,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=533,
  serialized_end=750,
)
_sym_db.RegisterEnumDescriptor(_DATASOURCE)

dataSource = enum_type_wrapper.EnumTypeWrapper(_DATASOURCE)
_REALTIMERECOP = _descriptor.EnumDescriptor(
  name='RealTimeRecOp',
  full_name='RealTimeRecOp',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RealTimeRecUnkonw', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RealTimeRecGetData', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RealTimeRecSetData', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=752,
  serialized_end=838,
)
_sym_db.RegisterEnumDescriptor(_REALTIMERECOP)

RealTimeRecOp = enum_type_wrapper.EnumTypeWrapper(_REALTIMERECOP)
StatusCodeSuccess = 0
StatusCodeInvalidRequest = 1
StatusCodeBshelfFail = 2
StatusCodeBshelfRedisErr = 3
UnknownSource = 0
XST_UserBehavior = 12
XST_UserProfile = 13
XST_Recall = 14
HHM_UserBehavior = 15
HHM_UserProfile = 16
HHM_Recall = 17
Abroad_UserBehavior = 19
Abroad_UserProfile = 20
Abroad_Recall = 21
RealTimeRecUnkonw = 0
RealTimeRecGetData = 1
RealTimeRecSetData = 2



_REALTIMEREQUEST = _descriptor.Descriptor(
  name='RealTimeRequest',
  full_name='RealTimeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='RealTimeRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='RealTimeRequest.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_type', full_name='RealTimeRequest.source_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operate', full_name='RealTimeRequest.operate', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=138,
)


_REALTIMERESPONSE = _descriptor.Descriptor(
  name='RealTimeResponse',
  full_name='RealTimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='RealTimeResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='RealTimeResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='RealTimeResponse.value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=217,
)


_TEST_DATA = _descriptor.Descriptor(
  name='test_data',
  full_name='test_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='test_data.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_id', full_name='test_data.str_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_data', full_name='test_data.str_data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=276,
)


_BASE_INFO = _descriptor.Descriptor(
  name='base_info',
  full_name='base_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='base_info.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='base_info.gender', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=319,
)


_USER = _descriptor.Descriptor(
  name='user',
  full_name='user',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test1', full_name='user.test1', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='base', full_name='user.base', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test2', full_name='user.test2', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=407,
)

_REALTIMEREQUEST.fields_by_name['source_type'].enum_type = _DATASOURCE
_REALTIMEREQUEST.fields_by_name['operate'].enum_type = _REALTIMERECOP
_REALTIMERESPONSE.fields_by_name['code'].enum_type = _STATUSCODE
_USER.fields_by_name['test1'].message_type = _TEST_DATA
_USER.fields_by_name['base'].message_type = _BASE_INFO
_USER.fields_by_name['test2'].message_type = _TEST_DATA
DESCRIPTOR.message_types_by_name['RealTimeRequest'] = _REALTIMEREQUEST
DESCRIPTOR.message_types_by_name['RealTimeResponse'] = _REALTIMERESPONSE
DESCRIPTOR.message_types_by_name['test_data'] = _TEST_DATA
DESCRIPTOR.message_types_by_name['base_info'] = _BASE_INFO
DESCRIPTOR.message_types_by_name['user'] = _USER
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
DESCRIPTOR.enum_types_by_name['dataSource'] = _DATASOURCE
DESCRIPTOR.enum_types_by_name['RealTimeRecOp'] = _REALTIMERECOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RealTimeRequest = _reflection.GeneratedProtocolMessageType('RealTimeRequest', (_message.Message,), {
  'DESCRIPTOR' : _REALTIMEREQUEST,
  '__module__' : 'disk_file_system_pb2'
  # @@protoc_insertion_point(class_scope:RealTimeRequest)
  })
_sym_db.RegisterMessage(RealTimeRequest)

RealTimeResponse = _reflection.GeneratedProtocolMessageType('RealTimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _REALTIMERESPONSE,
  '__module__' : 'disk_file_system_pb2'
  # @@protoc_insertion_point(class_scope:RealTimeResponse)
  })
_sym_db.RegisterMessage(RealTimeResponse)

test_data = _reflection.GeneratedProtocolMessageType('test_data', (_message.Message,), {
  'DESCRIPTOR' : _TEST_DATA,
  '__module__' : 'disk_file_system_pb2'
  # @@protoc_insertion_point(class_scope:test_data)
  })
_sym_db.RegisterMessage(test_data)

base_info = _reflection.GeneratedProtocolMessageType('base_info', (_message.Message,), {
  'DESCRIPTOR' : _BASE_INFO,
  '__module__' : 'disk_file_system_pb2'
  # @@protoc_insertion_point(class_scope:base_info)
  })
_sym_db.RegisterMessage(base_info)

user = _reflection.GeneratedProtocolMessageType('user', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'disk_file_system_pb2'
  # @@protoc_insertion_point(class_scope:user)
  })
_sym_db.RegisterMessage(user)


# @@protoc_insertion_point(module_scope)
