# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import behavior_pb2 as behavior__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='profile.proto',
  package='realtime_rec',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\rprofile.proto\x12\x0crealtime_rec\x1a\x0e\x62\x65havior.proto\"\xc7\x02\n\x0bUserProfile\x12)\n\tbase_info\x18\x01 \x01(\x0b\x32\x16.realtime_rec.BaseInfo\x12+\n\tpre_novel\x18\x02 \x01(\x0b\x32\x18.realtime_rec.Preference\x12+\n\tpre_comic\x18\x03 \x01(\x0b\x32\x18.realtime_rec.Preference\x12+\n\tpre_video\x18\x04 \x01(\x0b\x32\x18.realtime_rec.Preference\x12/\n\rpre_book_list\x18\x05 \x01(\x0b\x32\x18.realtime_rec.Preference\x12*\n\x08pre_post\x18\x06 \x01(\x0b\x32\x18.realtime_rec.Preference\x12)\n\x07pre_all\x18\x07 \x01(\x0b\x32\x18.realtime_rec.Preference'
  ,
  dependencies=[behavior__pb2.DESCRIPTOR,])




_USERPROFILE = _descriptor.Descriptor(
  name='UserProfile',
  full_name='realtime_rec.UserProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_info', full_name='realtime_rec.UserProfile.base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_novel', full_name='realtime_rec.UserProfile.pre_novel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_comic', full_name='realtime_rec.UserProfile.pre_comic', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_video', full_name='realtime_rec.UserProfile.pre_video', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_book_list', full_name='realtime_rec.UserProfile.pre_book_list', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_post', full_name='realtime_rec.UserProfile.pre_post', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_all', full_name='realtime_rec.UserProfile.pre_all', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=375,
)

_USERPROFILE.fields_by_name['base_info'].message_type = behavior__pb2._BASEINFO
_USERPROFILE.fields_by_name['pre_novel'].message_type = behavior__pb2._PREFERENCE
_USERPROFILE.fields_by_name['pre_comic'].message_type = behavior__pb2._PREFERENCE
_USERPROFILE.fields_by_name['pre_video'].message_type = behavior__pb2._PREFERENCE
_USERPROFILE.fields_by_name['pre_book_list'].message_type = behavior__pb2._PREFERENCE
_USERPROFILE.fields_by_name['pre_post'].message_type = behavior__pb2._PREFERENCE
_USERPROFILE.fields_by_name['pre_all'].message_type = behavior__pb2._PREFERENCE
DESCRIPTOR.message_types_by_name['UserProfile'] = _USERPROFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserProfile = _reflection.GeneratedProtocolMessageType('UserProfile', (_message.Message,), {
  'DESCRIPTOR' : _USERPROFILE,
  '__module__' : 'profile_pb2'
  # @@protoc_insertion_point(class_scope:realtime_rec.UserProfile)
  })
_sym_db.RegisterMessage(UserProfile)


# @@protoc_insertion_point(module_scope)
