# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recall.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import behavior_pb2 as behavior__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='recall.proto',
  package='realtime_rec',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0crecall.proto\x12\x0crealtime_rec\x1a\x0e\x62\x65havior.proto\"H\n\x0bRecallEvent\x12-\n\x0brecall_type\x18\x01 \x01(\x0e\x32\x18.realtime_rec.RECALLTYPE\x12\n\n\x02id\x18\x02 \x03(\x04\"h\n\nRecallList\x12)\n\tdata_type\x18\x01 \x01(\x0e\x32\x16.realtime_rec.DATATYPE\x12/\n\x0crecall_event\x18\x02 \x03(\x0b\x32\x19.realtime_rec.RecallEvent\"\x98\x02\n\x0eUserRecallList\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\'\n\x05novel\x18\x02 \x01(\x0b\x32\x18.realtime_rec.RecallList\x12\'\n\x05\x63omic\x18\x03 \x01(\x0b\x32\x18.realtime_rec.RecallList\x12\'\n\x05video\x18\x04 \x01(\x0b\x32\x18.realtime_rec.RecallList\x12+\n\tbook_list\x18\x05 \x01(\x0b\x32\x18.realtime_rec.RecallList\x12&\n\x04post\x18\x06 \x01(\x0b\x32\x18.realtime_rec.RecallList\x12%\n\x03\x61ll\x18\x07 \x01(\x0b\x32\x18.realtime_rec.RecallList*\x8f\x01\n\nRECALLTYPE\x12\x13\n\x0fRECALL_TYPE_ALL\x10\x00\x12\x18\n\x14RECALL_TYPE_CATEGORY\x10\x01\x12\x13\n\x0fRECALL_TYPE_NEW\x10\x02\x12\x13\n\x0fRECALL_TYPE_HOT\x10\x03\x12\x13\n\x0fRECALL_TYPE_ICF\x10\x04\x12\x13\n\x0fRECALL_TYPE_UCF\x10\x05'
  ,
  dependencies=[behavior__pb2.DESCRIPTOR,])

_RECALLTYPE = _descriptor.EnumDescriptor(
  name='RECALLTYPE',
  full_name='realtime_rec.RECALLTYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RECALL_TYPE_ALL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECALL_TYPE_CATEGORY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECALL_TYPE_NEW', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECALL_TYPE_HOT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECALL_TYPE_ICF', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECALL_TYPE_UCF', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=510,
  serialized_end=653,
)
_sym_db.RegisterEnumDescriptor(_RECALLTYPE)

RECALLTYPE = enum_type_wrapper.EnumTypeWrapper(_RECALLTYPE)
RECALL_TYPE_ALL = 0
RECALL_TYPE_CATEGORY = 1
RECALL_TYPE_NEW = 2
RECALL_TYPE_HOT = 3
RECALL_TYPE_ICF = 4
RECALL_TYPE_UCF = 5



_RECALLEVENT = _descriptor.Descriptor(
  name='RecallEvent',
  full_name='realtime_rec.RecallEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recall_type', full_name='realtime_rec.RecallEvent.recall_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='realtime_rec.RecallEvent.id', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=118,
)


_RECALLLIST = _descriptor.Descriptor(
  name='RecallList',
  full_name='realtime_rec.RecallList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_type', full_name='realtime_rec.RecallList.data_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recall_event', full_name='realtime_rec.RecallList.recall_event', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=224,
)


_USERRECALLLIST = _descriptor.Descriptor(
  name='UserRecallList',
  full_name='realtime_rec.UserRecallList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='realtime_rec.UserRecallList.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='novel', full_name='realtime_rec.UserRecallList.novel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comic', full_name='realtime_rec.UserRecallList.comic', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video', full_name='realtime_rec.UserRecallList.video', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='book_list', full_name='realtime_rec.UserRecallList.book_list', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post', full_name='realtime_rec.UserRecallList.post', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all', full_name='realtime_rec.UserRecallList.all', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=507,
)

_RECALLEVENT.fields_by_name['recall_type'].enum_type = _RECALLTYPE
_RECALLLIST.fields_by_name['data_type'].enum_type = behavior__pb2._DATATYPE
_RECALLLIST.fields_by_name['recall_event'].message_type = _RECALLEVENT
_USERRECALLLIST.fields_by_name['novel'].message_type = _RECALLLIST
_USERRECALLLIST.fields_by_name['comic'].message_type = _RECALLLIST
_USERRECALLLIST.fields_by_name['video'].message_type = _RECALLLIST
_USERRECALLLIST.fields_by_name['book_list'].message_type = _RECALLLIST
_USERRECALLLIST.fields_by_name['post'].message_type = _RECALLLIST
_USERRECALLLIST.fields_by_name['all'].message_type = _RECALLLIST
DESCRIPTOR.message_types_by_name['RecallEvent'] = _RECALLEVENT
DESCRIPTOR.message_types_by_name['RecallList'] = _RECALLLIST
DESCRIPTOR.message_types_by_name['UserRecallList'] = _USERRECALLLIST
DESCRIPTOR.enum_types_by_name['RECALLTYPE'] = _RECALLTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecallEvent = _reflection.GeneratedProtocolMessageType('RecallEvent', (_message.Message,), {
  'DESCRIPTOR' : _RECALLEVENT,
  '__module__' : 'recall_pb2'
  # @@protoc_insertion_point(class_scope:realtime_rec.RecallEvent)
  })
_sym_db.RegisterMessage(RecallEvent)

RecallList = _reflection.GeneratedProtocolMessageType('RecallList', (_message.Message,), {
  'DESCRIPTOR' : _RECALLLIST,
  '__module__' : 'recall_pb2'
  # @@protoc_insertion_point(class_scope:realtime_rec.RecallList)
  })
_sym_db.RegisterMessage(RecallList)

UserRecallList = _reflection.GeneratedProtocolMessageType('UserRecallList', (_message.Message,), {
  'DESCRIPTOR' : _USERRECALLLIST,
  '__module__' : 'recall_pb2'
  # @@protoc_insertion_point(class_scope:realtime_rec.UserRecallList)
  })
_sym_db.RegisterMessage(UserRecallList)


# @@protoc_insertion_point(module_scope)
