# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: similar_book.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='similar_book.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12similar_book.proto\".\n\x0b_32ByteItem\x12\n\n\x02id\x18\x01 \x01(\r\x12\x13\n\x0blanguage_id\x18\x02 \x01(\x04\"*\n\x0b_32ByteList\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c._32ByteItem')
)




__32BYTEITEM = _descriptor.Descriptor(
  name='_32ByteItem',
  full_name='_32ByteItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='_32ByteItem.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language_id', full_name='_32ByteItem.language_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=68,
)


__32BYTELIST = _descriptor.Descriptor(
  name='_32ByteList',
  full_name='_32ByteList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='_32ByteList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=112,
)

__32BYTELIST.fields_by_name['items'].message_type = __32BYTEITEM
DESCRIPTOR.message_types_by_name['_32ByteItem'] = __32BYTEITEM
DESCRIPTOR.message_types_by_name['_32ByteList'] = __32BYTELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_32ByteItem = _reflection.GeneratedProtocolMessageType('_32ByteItem', (_message.Message,), {
  'DESCRIPTOR' : __32BYTEITEM,
  '__module__' : 'similar_book_pb2'
  # @@protoc_insertion_point(class_scope:_32ByteItem)
  })
_sym_db.RegisterMessage(_32ByteItem)

_32ByteList = _reflection.GeneratedProtocolMessageType('_32ByteList', (_message.Message,), {
  'DESCRIPTOR' : __32BYTELIST,
  '__module__' : 'similar_book_pb2'
  # @@protoc_insertion_point(class_scope:_32ByteList)
  })
_sym_db.RegisterMessage(_32ByteList)


# @@protoc_insertion_point(module_scope)
